-- ========================================================
-- SCRIPT DE CRIAÇÃO DE TABELAS SUPABASE - CHAVE RESERVA
-- Execute este script no SQL Editor do seu Dashboard Supabase
-- ========================================================

-- 1. Tabela: projecao_mensal
CREATE TABLE IF NOT EXISTS public.projecao_mensal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month TEXT UNIQUE NOT NULL,
  clientes_ativos_meta NUMERIC DEFAULT 0,
  churn NUMERIC DEFAULT 0,
  novos_liquidos_meta NUMERIC DEFAULT 0,
  is_locked_novos BOOLEAN DEFAULT FALSE,
  novos_brutos_necessarios NUMERIC DEFAULT 0,
  mrr_meta NUMERIC DEFAULT 0,
  mrr_aluguel NUMERIC DEFAULT 0,
  mrr_pacotes NUMERIC DEFAULT 0,
  mrr_total NUMERIC DEFAULT 0,
  receita_empresa NUMERIC DEFAULT 0,
  comissao_vendas NUMERIC DEFAULT 0,
  comissao_suporte NUMERIC DEFAULT 0,
  novos_trafego NUMERIC DEFAULT 0,
  cac_trafego NUMERIC DEFAULT 0,
  investimento_trafego NUMERIC DEFAULT 0,
  novos_lista NUMERIC DEFAULT 0,
  contatos_frios NUMERIC DEFAULT 0,
  custo_lista_fria NUMERIC DEFAULT 0,
  novos_influencer NUMERIC DEFAULT 0,
  custo_1a_influencer NUMERIC DEFAULT 0,
  custo_recorrente_influencer NUMERIC DEFAULT 0,
  pro_labore_dev NUMERIC DEFAULT 0,
  pro_labore_gestor NUMERIC DEFAULT 0,
  pro_labore_mkt NUMERIC DEFAULT 0,
  pro_labore_fin NUMERIC DEFAULT 0,
  suporte_fixo NUMERIC DEFAULT 0,
  apoio_tecnico NUMERIC DEFAULT 0,
  sdr NUMERIC DEFAULT 0,
  infraestrutura NUMERIC DEFAULT 0,
  taxas_pagamento NUMERIC DEFAULT 0,
  impostos NUMERIC DEFAULT 0,
  resultado_bruto NUMERIC DEFAULT 0,
  resultado_liquido NUMERIC DEFAULT 0,
  receita_caixa NUMERIC DEFAULT 0,
  impostos_caixa_8 NUMERIC DEFAULT 0,
  resultado_caixa NUMERIC DEFAULT 0,
  saldo_caixa_acumulado NUMERIC DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabela: planos
CREATE TABLE IF NOT EXISTS public.planos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plano TEXT UNIQUE NOT NULL,
  mensal NUMERIC DEFAULT 0,
  anual_mensal NUMERIC DEFAULT 0,
  anual_vista NUMERIC DEFAULT 0,
  previsao_vendas NUMERIC DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabela: premissas
CREATE TABLE IF NOT EXISTS public.premissas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  premissa TEXT UNIQUE NOT NULL,
  valor TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabela: aluguel
CREATE TABLE IF NOT EXISTS public.aluguel (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plano TEXT NOT NULL,
  mensal NUMERIC DEFAULT 0,
  anual_mensal NUMERIC DEFAULT 0,
  anual_vista NUMERIC DEFAULT 0,
  previsao_vendas NUMERIC DEFAULT 0,
  vendido_base TEXT,
  previsao_lancamento TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabela: pacotes
CREATE TABLE IF NOT EXISTS public.pacotes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pacote TEXT NOT NULL,
  qtd NUMERIC DEFAULT 1,
  valor NUMERIC DEFAULT 0,
  previsao_vendas NUMERIC DEFAULT 0,
  vendido_base TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Tabela: equipe
CREATE TABLE IF NOT EXISTS public.equipe (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area TEXT NOT NULL,
  modelo TEXT,
  remuneracao TEXT,
  gatilho TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Tabela: infraestrutura
CREATE TABLE IF NOT EXISTS public.infraestrutura (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faixa TEXT NOT NULL,
  total NUMERIC DEFAULT 0,
  itens JSONB DEFAULT '[]'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Tabela: aquisicao
CREATE TABLE IF NOT EXISTS public.aquisicao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canal TEXT NOT NULL,
  participacao TEXT,
  regra TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Tabela: taxas_pagamento
CREATE TABLE IF NOT EXISTS public.taxas_pagamento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metodo TEXT NOT NULL,
  taxa_fixa NUMERIC DEFAULT 0,
  taxa_var NUMERIC DEFAULT 0,
  uso NUMERIC DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Tabela: resumo_executivo
CREATE TABLE IF NOT EXISTS public.resumo_executivo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_name TEXT UNIQUE NOT NULL,
  data JSONB DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Tabela: leads
CREATE TABLE IF NOT EXISTS public.leads (
  id TEXT PRIMARY KEY,
  nome TEXT NOT NULL,
  empresa TEXT,
  email TEXT,
  telefone TEXT,
  plano_interesse TEXT,
  mrr_estimado NUMERIC DEFAULT 0,
  canal TEXT,
  estagio TEXT,
  data_criacao DATE DEFAULT CURRENT_DATE,
  observacoes TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. Tabela: clientes
CREATE TABLE IF NOT EXISTS public.clientes (
  id TEXT PRIMARY KEY,
  nome TEXT NOT NULL,
  empresa TEXT,
  email TEXT,
  telefone TEXT,
  plano TEXT,
  mrr NUMERIC DEFAULT 0,
  modulos_adicionais JSONB DEFAULT '[]'::jsonb,
  metodo_pagamento TEXT,
  status TEXT DEFAULT 'Ativo',
  data_entrada DATE DEFAULT CURRENT_DATE,
  data_cancelamento DATE,
  canal_origem TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 13. Tabela: lancamentos_diarios
CREATE TABLE IF NOT EXISTS public.lancamentos_diarios (
  id TEXT PRIMARY KEY,
  data DATE DEFAULT CURRENT_DATE,
  novos_clientes INTEGER DEFAULT 0,
  gasto_trafego NUMERIC DEFAULT 0,
  comissoes_pagas NUMERIC DEFAULT 0,
  custos_operacionais NUMERIC DEFAULT 0,
  receita_reais NUMERIC DEFAULT 0,
  observacoes TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 14. Tabela de estado global do app (kv store de backup ilimitado)
CREATE TABLE IF NOT EXISTS public.app_state (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- HABILITAR PERMISSÕES PÚBLICAS DE LEITURA E ESCRITA PARA TODAS AS TABELAS
ALTER TABLE public.projecao_mensal ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.planos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.premissas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.aluguel ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pacotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipe ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.infraestrutura ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.aquisicao ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.taxas_pagamento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resumo_executivo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lancamentos_diarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_state ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS PERMISSIVAS PARA LEITURA E GRAVAÇÃO
DROP POLICY IF EXISTS "Public read write projecao_mensal" ON public.projecao_mensal;
CREATE POLICY "Public read write projecao_mensal" ON public.projecao_mensal FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public read write planos" ON public.planos;
CREATE POLICY "Public read write planos" ON public.planos FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public read write premissas" ON public.premissas;
CREATE POLICY "Public read write premissas" ON public.premissas FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public read write aluguel" ON public.aluguel;
CREATE POLICY "Public read write aluguel" ON public.aluguel FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public read write pacotes" ON public.pacotes;
CREATE POLICY "Public read write pacotes" ON public.pacotes FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public read write equipe" ON public.equipe;
CREATE POLICY "Public read write equipe" ON public.equipe FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public read write infraestrutura" ON public.infraestrutura;
CREATE POLICY "Public read write infraestrutura" ON public.infraestrutura FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public read write aquisicao" ON public.aquisicao;
CREATE POLICY "Public read write aquisicao" ON public.aquisicao FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public read write taxas_pagamento" ON public.taxas_pagamento;
CREATE POLICY "Public read write taxas_pagamento" ON public.taxas_pagamento FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public read write resumo_executivo" ON public.resumo_executivo;
CREATE POLICY "Public read write resumo_executivo" ON public.resumo_executivo FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public read write leads" ON public.leads;
CREATE POLICY "Public read write leads" ON public.leads FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public read write clientes" ON public.clientes;
CREATE POLICY "Public read write clientes" ON public.clientes FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public read write lancamentos_diarios" ON public.lancamentos_diarios;
CREATE POLICY "Public read write lancamentos_diarios" ON public.lancamentos_diarios FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public read write app_state" ON public.app_state;
CREATE POLICY "Public read write app_state" ON public.app_state FOR ALL USING (true) WITH CHECK (true);
